### ISSUE TITLE
arm64 image

### ISSUE THREAD

**Issue by firestrife23** [dangrie158/dolce#11]
Just a feature request, would like an arm64 image for Raspberry Pi.

**Comment by dangrie158** [comment]
Hi,

I just released [v2.4.0](https://hub.docker.com/layers/dangrie158/dolce/v2.4.0/images/sha256-185fe3bf3b389ec1a25a904edd7736f45f54c63215669066f3dc5c574d42d8dc?context=repo) which is based on [lukechannings/deno](https://hub.docker.com/r/lukechannings/deno). 

This means native arm64 builds are now available. Sadly I had to change to an ubuntu base image instead of the alpine used before which means that the image size slightly increased.

You should now be able to run the `dangrie158/dolce:latest` image on your Pi :)
