### ISSUE TITLE
Error while launching container

### ISSUE THREAD

**Issue by mariomaz87** [dangrie158/dolce#18]
Hi, 
In the latest days Dolce is showing this message in the log and it seems not be working:

⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
error: empty host

My docker compose is:

version: "3"
services:

  dolce:
    image: dangrie158/dolce:v2.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment: 
      - TELEGRAM_HTTP_TOKEN=xxxxxxx
      - TELEGRAM_RECIPIENT_IDS=xxxxxxx
      - DOLCE_EVENTS=die:kill:health_status
      - DOLCE_MIN_TIMEOUT=30
      - DOLCE_MULTIPLIER=0
    restart: unless-stopped

Thanks!

**Comment by dangrie158** [comment]
Hi,
thanks for the report!

seems like this issue was introduced when updating deno to fix a problem with the docker-socket-proxy support so this slipped past testing.

I just fixed the issue and created a new release 2.10 which also uses the official denoland docker containers since they are now available for amr64 as well.
