### ISSUE TITLE
Add support for Mattermost/Slack notifications

### ISSUE THREAD

**Issue by kehoecj** [dangrie158/dolce#8]
Really like the concept of this tool and the implementation. Can this be extended to support other tools like mattermost/slack notifications? I could that as a popular integration

**Comment by dangrie158** [comment]
Sure. I want to add more notification methods as I go, however I want to do some refactoring first and setup a proper documentation site to keep all methods discoverable without a pages-long readme. I'll keep you updated in here

**Comment by Riscue** [comment]
I think you can integrate with almost all notification platform via [caronc/apprise](https://github.com/caronc/apprise) easily.

**Comment by dangrie158** [comment]
Hi,

I just bumped the version to v2.3.0 in a3684f5 which includes cb2995b to add support for Apprise.

I didn't want to vendor Apprise into the container since not all users are going to need it, but the newest release now supports talking to a Apprise API.

You can find detailed instructions in the documentation for this release: https://dangrie158.github.io/dolce/v2.3.0/notifiers/apprise/

Thanks for the suggestion and the tip with apprise :)
